"""Admin authentication for the 3-way live human chat takeover.

Real Arun logs in through a signed admin token embedded in the 1-Click Join
link generated by Telegram alerts. The token is derived from the session id
plus a shared secret, keeping the webhook/join flow stateless.
"""
import hashlib
import os

ADMIN_SECRET_KEY = os.getenv("ADMIN_SECRET_KEY", "aruncore_secret_key_2026")


def generate_admin_token(session_id: str) -> str:
    raw = f"{session_id}:{ADMIN_SECRET_KEY}".encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:16]


def verify_admin_token(session_id: str, token: str) -> bool:
    if not session_id or not token:
        return False
    expected = generate_admin_token(session_id)
    return token.strip() == expected