import { ProjectItem } from "./types";

export const PROJECTS_DATA: ProjectItem[] = [
  {
    id: "skills",
    name: "skills",
    title: "AI Agent Skills Repository",
    category: "Agents & Tools",
    description: "Modular skills & instructions library powering autonomous agent capabilities, workflow extensions, and standardized tool schemas.",
    githubUrl: "https://github.com/neural-arun/skills",
    techStack: ["Markdown", "YAML", "Python", "JSON Schemas"],
    highlights: ["Reusable agent skill definitions", "Standardized MCP tool specs", "Modular workflow execution"],
    suggestedPrompt: "Tell me about your AI Agent Skills repository and how you structure agent capabilities.",
    updatedAt: "2026-07-24T10:19:09Z",
    updatedAtLabel: "Updated Jul 2026"
  },
  {
    id: "neural-arun",
    name: "neural-arun",
    title: "Neural Arun Core Ecosystem",
    category: "Agents & Tools",
    description: "Core personal portfolio repository and identity index linking AI Digital Twin architectures, notes, and system experiments.",
    githubUrl: "https://github.com/neural-arun/neural-arun",
    techStack: ["Python", "FastAPI", "Next.js", "Markdown"],
    highlights: ["Central identity graph", "Data ingestion manifests", "System configuration"],
    suggestedPrompt: "What is the Neural Arun Core Ecosystem project?",
    updatedAt: "2026-07-23T08:26:56Z",
    updatedAtLabel: "Updated Jul 2026"
  },
  {
    id: "neet_bot",
    name: "neet-bot",
    title: "NEET Medical Exam Prep Agent",
    category: "Education",
    description: "Dedicated AI tutor and assessment system for medical entrance exam (NEET) syllabus. Delivers instant concept breakdowns, practice questions, and grounded medical answers.",
    githubUrl: "https://github.com/neural-arun/neet-bot",
    techStack: ["Python", "LangChain", "Vector Memory", "FastAPI", "React"],
    highlights: ["Instant concept retrieval", "Automated mock test generation", "Personalized learning pathways"],
    suggestedPrompt: "How does NEET Bot help students prepare for medical entrance exams?",
    updatedAt: "2026-07-22T14:10:23Z",
    updatedAtLabel: "Updated Jul 2026"
  },
  {
    id: "api_projects",
    name: "api_projects",
    title: "FastAPI & Microservices Architecture Suite",
    category: "Agents & Tools",
    description: "Collection of high-performance FastAPI microservices, streaming endpoints, authentication layers, and async queue workers.",
    githubUrl: "https://github.com/neural-arun/api_projects",
    techStack: ["Python", "FastAPI", "Pydantic", "Redis", "Docker"],
    highlights: ["NDJSON streaming response layers", "Async task queue management", "OpenAPI spec generators"],
    suggestedPrompt: "Tell me about your API Projects suite and microservices backend patterns.",
    updatedAt: "2026-07-21T07:45:00Z",
    updatedAtLabel: "Updated Jul 2026"
  },
  {
    id: "mcp",
    name: "mcp",
    title: "Model Context Protocol (MCP) Server Suite",
    category: "Agents & Tools",
    description: "Custom Model Context Protocol (MCP) servers exposing specialized database tools, file system inspectors, and custom external API connectors to agent runtimes.",
    githubUrl: "https://github.com/neural-arun/mcp",
    techStack: ["TypeScript", "Python", "MCP SDK", "JSON-RPC"],
    highlights: ["Standardized tool discovery", "Secure schema validation", "Seamless Claude & AGY tool integration"],
    suggestedPrompt: "How do you leverage Model Context Protocol (MCP) in your agentic workflows?",
    updatedAt: "2026-07-06T06:00:22Z",
    updatedAtLabel: "Updated Jul 2026"
  },
  {
    id: "uday_bpsc",
    name: "uday_bpsc",
    title: "Uday BPSC Educational Portal",
    category: "Education",
    description: "Online learning & question bank system tailored for competitive state examination candidates with personalized performance analytics.",
    githubUrl: "https://github.com/neural-arun/uday_bpsc",
    techStack: ["Python", "Django", "PostgreSQL", "Bootstrap"],
    highlights: ["Question bank tagging system", "Mock test analytics", "Student progress dashboard"],
    suggestedPrompt: "What is Uday BPSC and how does it support exam preparation?",
    updatedAt: "2026-07-05T13:24:42Z",
    updatedAtLabel: "Updated Jul 2026"
  },
  {
    id: "01_manage_patient_task",
    name: "01_manage_patient_task",
    title: "Clinical Patient Task Manager",
    category: "Healthcare",
    description: "Healthcare workflow engine prioritizing clinical tasks, tracking patient care workflows, and alerting medical staff to care deadlines.",
    githubUrl: "https://github.com/neural-arun/01_manage_patient_task",
    techStack: ["Python", "FastAPI", "PostgreSQL", "Celery", "Redis"],
    highlights: ["Real-time patient task priority queues", "Clinical rule engine", "HIPAA-conscious data pipelines"],
    suggestedPrompt: "Tell me about your Patient Task Management system for healthcare workflow automation.",
    updatedAt: "2026-06-28T11:34:30Z",
    updatedAtLabel: "Updated Jun 2026"
  },
  {
    id: "med_coach",
    name: "med_coach",
    title: "MedCoach AI Clinical Assistant",
    category: "Healthcare",
    description: "Medical education & decision support platform assisting healthcare professionals and students with grounded medical knowledge search and interactive case studies.",
    githubUrl: "https://github.com/neural-arun/med_coach",
    techStack: ["Python", "FastAPI", "OpenAI", "ChromaDB"],
    highlights: ["Grounded clinical reference retrieval", "Human-in-the-loop validation layer", "Case study generation"],
    suggestedPrompt: "What was your approach in designing MedCoach for healthcare professionals?",
    updatedAt: "2026-06-16T18:29:39Z",
    updatedAtLabel: "Updated Jun 2026"
  },
  {
    id: "valueable_notes",
    name: "valueable_notes",
    title: "Curated Technical Knowledge Repository",
    category: "Education",
    description: "Structured markdown knowledge base indexing machine learning, system design patterns, and medical AI literature.",
    githubUrl: "https://github.com/neural-arun/valueable_notes",
    techStack: ["Markdown", "Python", "Indexing Scripts"],
    highlights: ["Categorized topic hierarchies", "Semantic search readiness", "System architecture notes"],
    suggestedPrompt: "Tell me about your Valuable Notes repository.",
    updatedAt: "2026-05-07T10:11:23Z",
    updatedAtLabel: "Updated May 2026"
  },
  {
    id: "deep_research",
    name: "deep_research",
    title: "Autonomous Deep Research Agent",
    category: "Agents & Tools",
    description: "Multi-step autonomous web research agent that iteratively inspects technical documentation, synthesizes structured reports, and cites authoritative sources.",
    githubUrl: "https://github.com/neural-arun/deep_research",
    techStack: ["Python", "Playwright", "LangChain", "Tavily API", "OpenAI"],
    highlights: ["Iterative search & verification loop", "Automatic report generation", "Source citation matrix"],
    suggestedPrompt: "How does your Deep Research Agent execute multi-step web investigation?",
    updatedAt: "2026-05-06T23:50:16Z",
    updatedAtLabel: "Updated May 2026"
  },
  {
    id: "notes_maker",
    name: "Notes_maker_via_youtube_or_subs",
    title: "YouTube & Subtitle Knowledge Extractor",
    category: "Automation & Scraping",
    description: "Automated engine that ingests video lectures and transcripts, generating structured study notes, flashcards, and topic indexes.",
    githubUrl: "https://github.com/neural-arun/Notes_maker_via_youtube_or_subs",
    techStack: ["Python", "yt-dlp", "Whisper", "OpenAI"],
    highlights: ["Automated transcript cleaning", "Key summary extraction", "Flashcard generation"],
    suggestedPrompt: "How does the YouTube Notes Extractor convert video lectures into study guides?",
    updatedAt: "2026-05-04T22:29:02Z",
    updatedAtLabel: "Updated May 2026"
  },
  {
    id: "aruncore",
    name: "ArunCore",
    title: "ArunCore AI Digital Twin & RAG Engine",
    category: "RAG & AI",
    description: "Stateful AI Digital Twin engine combining ChromaDB vector search, BM25 keyword matching, Cohere Reranker, live GitHub API inspection, and instant Telegram phone notification handoff.",
    githubUrl: "https://github.com/neural-arun/ArunCore",
    techStack: ["Python", "FastAPI", "ChromaDB", "BM25", "Cohere Reranker", "LangChain", "Telegram API"],
    highlights: ["Hybrid Vector + BM25 Search", "Cohere Cross-Encoder Reranker", "Stateful rolling memory", "Telegram phone alerts"],
    suggestedPrompt: "Explain how ArunCore's hybrid RAG and stateful memory work.",
    updatedAt: "2026-04-21T21:10:16Z",
    updatedAtLabel: "Updated Apr 2026"
  },
  {
    id: "personal_learning_lab",
    name: "personal_learning_lab",
    title: "Personal AI Learning & Sandbox Lab",
    category: "Education",
    description: "Hands-on technical laboratory for prototyping new LLM techniques, prompt synthesis strategies, and vector indexing benchmarks.",
    githubUrl: "https://github.com/neural-arun/personal_learning_lab",
    techStack: ["Python", "Jupyter", "PyTorch", "Transformers"],
    highlights: ["LLM benchmarking suites", "RAG retrieval hit-rate evals", "Prompt experimentation"],
    suggestedPrompt: "What experiments do you run in your Personal Learning Lab?",
    updatedAt: "2026-04-14T14:44:25Z",
    updatedAtLabel: "Updated Apr 2026"
  },
  {
    id: "web_wizard",
    name: "web_wizard",
    title: "Web Wizard Autonomous UI Generator",
    category: "Agents & Tools",
    description: "AI agent inspecting wireframe designs, generating production HTML/CSS/JS code, and validating layout responsive constraints in real-time.",
    githubUrl: "https://github.com/neural-arun/web_wizard",
    techStack: ["Python", "Playwright", "FastAPI", "Vision LLMs"],
    highlights: ["Visual screenshot evaluation", "Iterative UI refinement loop", "Clean code output"],
    suggestedPrompt: "What does the Web Wizard agent do for automated UI generation?",
    updatedAt: "2026-04-08T06:10:58Z",
    updatedAtLabel: "Updated Apr 2026"
  },
  {
    id: "legal_rag_system",
    name: "legal_RAG_system",
    title: "Indian Legal RAG System",
    category: "RAG & AI",
    description: "Zero-hallucination legal RAG pipeline built for Indian legal documents (IPC, Constitution, case precedents) with document-structure aware chunking and Groq synthesis.",
    githubUrl: "https://github.com/neural-arun/legal_RAG_system",
    techStack: ["Python", "PyPDF", "LangChain", "ChromaDB", "Groq", "Llama-3.3-70B"],
    highlights: ["Structure-aware chunking (IPC by section, Constitution by article)", "Exact reference lookup + Semantic fallback", "Grounded zero-hallucination policy"],
    suggestedPrompt: "How did you build the Indian Legal RAG System and handle document-specific chunking?",
    updatedAt: "2026-04-04T19:38:26Z",
    updatedAtLabel: "Updated Apr 2026"
  },
  {
    id: "result_anomaly",
    name: "result_anomaly",
    title: "Academic Result Anomaly Detection Engine",
    category: "Automation & Scraping",
    description: "Statistical and machine learning pipeline for detecting scoring anomalies and grade distribution outliers in educational datasets.",
    githubUrl: "https://github.com/neural-arun/result_anomaly",
    techStack: ["Python", "Pandas", "Scikit-Learn", "Matplotlib"],
    highlights: ["Outlier detection algorithms", "Data cleanup pipelines", "Visual report generators"],
    suggestedPrompt: "Tell me about the Result Anomaly Detection project.",
    updatedAt: "2026-04-03T10:05:59Z",
    updatedAtLabel: "Updated Apr 2026"
  },
  {
    id: "personal_ai_agent",
    name: "personal_ai_agent",
    title: "Personal Task & Reasoning AI Assistant",
    category: "Agents & Tools",
    description: "Custom terminal and web AI assistant managing daily developer workflows, notes indexing, and automated reminders.",
    githubUrl: "https://github.com/neural-arun/personal_ai_agent",
    techStack: ["Python", "Click CLI", "OpenAI", "SQLite"],
    highlights: ["Local task prioritization", "Natural language queries", "CLI interface"],
    suggestedPrompt: "Tell me about your Personal AI Agent CLI.",
    updatedAt: "2026-03-30T15:43:31Z",
    updatedAtLabel: "Updated Mar 2026"
  },
  {
    id: "Agentic_AI_Projects",
    name: "Agentic_AI_Projects",
    title: "Agentic AI Architecture Patterns",
    category: "RAG & AI",
    description: "Collection of production design patterns for multi-agent collaboration, tool calling, memory management, and human-in-the-loop workflows.",
    githubUrl: "https://github.com/neural-arun/Agentic_AI_Projects",
    techStack: ["Python", "LangChain", "LangGraph", "FastAPI"],
    highlights: ["State machine workflows", "Multi-agent coordination", "Tool routing patterns"],
    suggestedPrompt: "What agentic AI architectural patterns do you implement here?",
    updatedAt: "2026-03-22T07:20:56Z",
    updatedAtLabel: "Updated Mar 2026"
  },
  {
    id: "working_with_LLMs",
    name: "working_with_LLMs",
    title: "LLM Integration & Fine-Tuning Guide",
    category: "RAG & AI",
    description: "Practical guide, code examples, and benchmarks for building production applications with large language models.",
    githubUrl: "https://github.com/neural-arun/working_with_LLMs",
    techStack: ["Python", "OpenAI API", "Anthropic SDK", "Groq API"],
    highlights: ["Structured JSON output enforcement", "Prompt optimization", "Cost & latency benchmarks"],
    suggestedPrompt: "Tell me about your Working With LLMs repository.",
    updatedAt: "2026-03-18T04:25:43Z",
    updatedAtLabel: "Updated Mar 2026"
  },
  {
    id: "neural_arun_labs",
    name: "neural_arun_labs",
    title: "Neural Arun Research Laboratories",
    category: "Agents & Tools",
    description: "Experimental repository testing cutting-edge research papers in retrieval augmentation, graph RAG, and multi-modal models.",
    githubUrl: "https://github.com/neural-arun/neural_arun_labs",
    techStack: ["Python", "PyTorch", "NetworkX", "ChromaDB"],
    highlights: ["Graph RAG experiments", "Multi-modal retrieval", "Custom embeddings testing"],
    suggestedPrompt: "What research experiments are in Neural Arun Labs?",
    updatedAt: "2026-03-15T04:28:39Z",
    updatedAtLabel: "Updated Mar 2026"
  },
  {
    id: "real_estate_scraper",
    name: "real_state_listing_scraper",
    title: "Real Estate Market Scraper & Anomaly Detector",
    category: "Automation & Scraping",
    description: "Scalable web scraping & analytical pipeline for property listings, extracting price trends, location scores, and undervalued property alerts.",
    githubUrl: "https://github.com/neural-arun/real_state_listing_scraper",
    techStack: ["Python", "BeautifulSoup", "Playwright", "Pandas", "Scikit-Learn"],
    highlights: ["Anti-bot bypass handling", "Structured price evaluation engine", "Automated anomaly alerts"],
    suggestedPrompt: "How did you build the Real Estate Listing Scraper?",
    updatedAt: "2026-03-14T10:48:12Z",
    updatedAtLabel: "Updated Mar 2026"
  },
  {
    id: "relic_rush_game",
    name: "relic-rush-game",
    title: "Relic Rush Interactive Web Game",
    category: "Agents & Tools",
    description: "Web browser game showcasing interactive Canvas animations, state machines, and real-time user physics engine.",
    githubUrl: "https://github.com/neural-arun/relic-rush-game",
    techStack: ["JavaScript", "HTML5 Canvas", "CSS3", "Web Audio API"],
    highlights: ["60 FPS Canvas rendering", "State machine architecture", "Retro audio effects"],
    suggestedPrompt: "Tell me about the Relic Rush web game project!",
    updatedAt: "2026-02-21T16:53:58Z",
    updatedAtLabel: "Updated Feb 2026"
  }
];
